export interface Ferramenta {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  category: string;
  relatedBlogSlug: string;
  relatedBlogTitle: string;
  seoTitle: string;
  seoDescription: string;
}

export const ferramentas: Ferramenta[] = [
  {
    slug: "calculadora-roi",
    name: "Calculadora de ROI",
    shortName: "ROI",
    description: "Calcule o retorno sobre investimento de qualquer ação ou campanha.",
    longDescription: "Descubra o retorno exato de cada investimento: campanhas de marketing, contratações, equipamentos ou qualquer iniciativa comercial. Tome decisões baseadas em dados, não em suposição.",
    category: "Financeiro",
    relatedBlogSlug: "kpis-essenciais-para-empresas",
    relatedBlogTitle: "KPIs Essenciais para Empresas: O Que Realmente Importa Medir",
    seoTitle: "Calculadora de ROI Grátis — Retorno sobre Investimento | V3X",
    seoDescription: "Calcule o ROI de qualquer investimento em segundos. Fórmula, interpretação e benchmark incluso. Ferramenta gratuita do Grupo V3X.",
  },
  {
    slug: "calculadora-cac",
    name: "Calculadora de CAC",
    shortName: "CAC",
    description: "Descubra quanto sua empresa gasta para conquistar cada novo cliente.",
    longDescription: "O Custo de Aquisição de Cliente (CAC) é um dos indicadores mais críticos da saúde comercial. Saiba exatamente quanto custa cada cliente novo e compare com o valor que ele gera.",
    category: "Comercial",
    relatedBlogSlug: "cac-custo-de-aquisicao-de-clientes",
    relatedBlogTitle: "CAC: O Indicador que Determina se Seu Negócio É Sustentável",
    seoTitle: "Calculadora de CAC Grátis — Custo de Aquisição de Cliente | V3X",
    seoDescription: "Calcule o CAC da sua empresa gratuitamente. Descubra se o custo por cliente novo está dentro do saudável para o seu modelo de negócio.",
  },
  {
    slug: "calculadora-ticket-medio",
    name: "Calculadora de Ticket Médio",
    shortName: "Ticket Médio",
    description: "Calcule o valor médio por venda e identifique oportunidades de crescimento.",
    longDescription: "Ticket médio baixo significa que você precisa de mais vendas para crescer. Saiba exatamente onde você está e quanto precisa aumentar para atingir sua meta de receita.",
    category: "Comercial",
    relatedBlogSlug: "como-aumentar-ticket-medio",
    relatedBlogTitle: "Como Aumentar o Ticket Médio: Estratégias Práticas para PMEs",
    seoTitle: "Calculadora de Ticket Médio Grátis | V3X",
    seoDescription: "Calcule o ticket médio da sua empresa e descubra o impacto no faturamento. Ferramenta gratuita com benchmark por segmento.",
  },
  {
    slug: "calculadora-conversao",
    name: "Calculadora de Conversão",
    shortName: "Conversão",
    description: "Meça a taxa de conversão do seu funil e descubra onde estão os gargalos.",
    longDescription: "A taxa de conversão revela a eficiência do seu processo comercial. Calcule onde o funil está vazando e quanto receita adicional uma melhoria de 5% pode gerar.",
    category: "Comercial",
    relatedBlogSlug: "conversao-comercial",
    relatedBlogTitle: "Conversão Comercial: Como Vender Mais com os Mesmos Leads",
    seoTitle: "Calculadora de Taxa de Conversão Grátis | V3X",
    seoDescription: "Calcule a taxa de conversão de vendas e descubra o impacto no faturamento. Benchmark por etapa do funil incluso.",
  },
  {
    slug: "calculadora-comissao",
    name: "Calculadora de Comissão",
    shortName: "Comissão",
    description: "Calcule comissões de vendas com precisão — para vendedor e para a empresa.",
    longDescription: "Evite disputas e erros no fechamento de comissões. Calcule o valor exato da comissão, o líquido que fica para a empresa e o custo real de cada venda.",
    category: "Comercial",
    relatedBlogSlug: "como-montar-equipe-de-vendas",
    relatedBlogTitle: "Como Montar uma Equipe de Vendas de Alta Performance",
    seoTitle: "Calculadora de Comissão de Vendas Grátis | V3X",
    seoDescription: "Calcule comissões de vendas em segundos. Valor para o vendedor, líquido para a empresa e custo total da venda.",
  },
  {
    slug: "calculadora-meta-comercial",
    name: "Calculadora de Meta Comercial",
    shortName: "Meta Comercial",
    description: "Defina quantas vendas e leads sua equipe precisa para atingir a meta de receita.",
    longDescription: "Transforme uma meta de faturamento em metas operacionais claras: quantas vendas fechar, quantos leads gerar e qual conversão manter. Planejamento comercial baseado em dados.",
    category: "Planejamento",
    relatedBlogSlug: "metas-comerciais",
    relatedBlogTitle: "Metas Comerciais: Como Definir Metas que o Time Realmente Persegue",
    seoTitle: "Calculadora de Meta Comercial Grátis | V3X",
    seoDescription: "Defina metas comerciais realistas: vendas, leads e conversão necessária para atingir sua meta de receita. Ferramenta gratuita.",
  },
  {
    slug: "calculadora-leads-necessarios",
    name: "Calculadora de Leads Necessários",
    shortName: "Leads",
    description: "Descubra quantos leads gerar para atingir sua meta de vendas.",
    longDescription: "Com base na sua taxa de conversão atual, calcule exatamente quantos leads você precisa gerar por mês para fechar a quantidade de vendas desejada. Planejamento de topo de funil preciso.",
    category: "Marketing",
    relatedBlogSlug: "funil-de-vendas-como-estruturar",
    relatedBlogTitle: "Funil de Vendas: Como Estruturar do Lead ao Fechamento",
    seoTitle: "Calculadora de Leads Necessários Grátis | V3X",
    seoDescription: "Calcule quantos leads você precisa gerar por mês para atingir sua meta de vendas. Baseado na sua taxa de conversão real.",
  },
  {
    slug: "calculadora-pipeline-comercial",
    name: "Calculadora de Pipeline Comercial",
    shortName: "Pipeline",
    description: "Projete a receita do seu pipeline atual e identifique se a meta está ao alcance.",
    longDescription: "Com base nos leads ativos no pipeline, na taxa de conversão e no ticket médio, projete a receita esperada do mês. Saiba com antecedência se precisa acelerar a prospecção.",
    category: "Comercial",
    relatedBlogSlug: "indicadores-de-vendas",
    relatedBlogTitle: "Indicadores de Vendas: O Dashboard Mínimo para Times Comerciais",
    seoTitle: "Calculadora de Pipeline Comercial Grátis | V3X",
    seoDescription: "Projete a receita do seu pipeline de vendas. Calcule vendas previstas e identifique gaps na meta comercial.",
  },
  {
    slug: "calculadora-break-even",
    name: "Calculadora de Break-even",
    shortName: "Break-even",
    description: "Descubra quantas unidades vender para cobrir todos os custos e começar a lucrar.",
    longDescription: "O ponto de equilíbrio (break-even) é o mínimo que sua empresa precisa vender para não ter prejuízo. Calcule em unidades e em receita para planejar metas realistas.",
    category: "Financeiro",
    relatedBlogSlug: "como-aumentar-margem-de-lucro",
    relatedBlogTitle: "Como Aumentar a Margem de Lucro Sem Aumentar o Faturamento",
    seoTitle: "Calculadora de Break-even (Ponto de Equilíbrio) Grátis | V3X",
    seoDescription: "Calcule o ponto de equilíbrio da sua empresa em unidades e receita. Saiba o mínimo que precisa vender para cobrir todos os custos.",
  },
  {
    slug: "calculadora-margem-lucro",
    name: "Calculadora de Margem de Lucro",
    shortName: "Margem",
    description: "Calcule a margem líquida e descubra quanto sobra de verdade após todos os custos.",
    longDescription: "Faturamento alto não garante lucro. Calcule a margem de lucro real da sua empresa ou produto e compare com o benchmark do seu setor.",
    category: "Financeiro",
    relatedBlogSlug: "gestao-financeira-empresarial",
    relatedBlogTitle: "Gestão Financeira Empresarial: O Guia para Donos de PME",
    seoTitle: "Calculadora de Margem de Lucro Grátis | V3X",
    seoDescription: "Calcule a margem de lucro líquida do seu negócio. Descubra quanto sobra de verdade após todos os custos e compare com o benchmark do setor.",
  },
  {
    slug: "calculadora-markup",
    name: "Calculadora de Markup",
    shortName: "Markup",
    description: "Calcule o preço de venda correto para cobrir custos e garantir sua margem.",
    longDescription: "Precificar errado é o erro mais comum nas PMEs. Calcule o markup ideal com base nos seus custos, despesas, impostos e margem desejada para nunca vender no prejuízo.",
    category: "Financeiro",
    relatedBlogSlug: "gestao-financeira-empresarial",
    relatedBlogTitle: "Gestão Financeira Empresarial: O Guia para Donos de PME",
    seoTitle: "Calculadora de Markup e Preço de Venda Grátis | V3X",
    seoDescription: "Calcule o markup e o preço de venda correto para cobrir todos os custos e garantir sua margem de lucro. Fórmula completa.",
  },
  {
    slug: "calculadora-ltv",
    name: "Calculadora de LTV",
    shortName: "LTV",
    description: "Calcule o valor total que um cliente gera durante todo o relacionamento com sua empresa.",
    longDescription: "O Lifetime Value (LTV) define quanto cada cliente vale para você ao longo do tempo. Confronte com o CAC para saber se seu modelo de aquisição é sustentável.",
    category: "Comercial",
    relatedBlogSlug: "ltv-lifetime-value",
    relatedBlogTitle: "LTV: Por que o Valor Vitalício do Cliente Determina Seu Crescimento",
    seoTitle: "Calculadora de LTV (Lifetime Value) Grátis | V3X",
    seoDescription: "Calcule o LTV dos seus clientes e a relação LTV:CAC. Descubra se seu modelo de aquisição de clientes é financeiramente sustentável.",
  },
  {
    slug: "calculadora-churn",
    name: "Calculadora de Churn",
    shortName: "Churn",
    description: "Meça a taxa de cancelamento e projete o impacto na receita recorrente.",
    longDescription: "Churn alto é um vazamento silencioso que impede o crescimento. Calcule a taxa de cancelamento mensal e anual e veja quanto receita você está perdendo.",
    category: "Recorrência",
    relatedBlogSlug: "ltv-lifetime-value",
    relatedBlogTitle: "LTV: Por que o Valor Vitalício do Cliente Determina Seu Crescimento",
    seoTitle: "Calculadora de Churn Rate Grátis | V3X",
    seoDescription: "Calcule a taxa de churn mensal e anual da sua base de clientes. Veja o impacto no crescimento e quanto receita está perdendo.",
  },
  {
    slug: "calculadora-mrr",
    name: "Calculadora de MRR",
    shortName: "MRR",
    description: "Calcule a receita recorrente mensal do seu negócio por plano ou segmento.",
    longDescription: "MRR (Monthly Recurring Revenue) é o indicador central de saúde para negócios de recorrência. Calcule o MRR total por plano, o ARR projetado e identifique qual segmento mais contribui.",
    category: "Recorrência",
    relatedBlogSlug: "escalabilidade-o-que-e",
    relatedBlogTitle: "Escalabilidade: O Que é e Como Construir um Negócio que Escala",
    seoTitle: "Calculadora de MRR e ARR Grátis | V3X",
    seoDescription: "Calcule o MRR (receita recorrente mensal) e ARR da sua empresa por plano. Indicador essencial para negócios de assinatura.",
  },
  {
    slug: "calculadora-crescimento-mensal",
    name: "Calculadora de Crescimento Mensal",
    shortName: "Crescimento",
    description: "Meça o crescimento mês a mês e projete o faturamento anual com base na taxa atual.",
    longDescription: "Crescimento consistente é o sinal mais importante de empresa saudável. Calcule a taxa de crescimento mensal e veja a projeção do que esse ritmo representa em 12 meses.",
    category: "Financeiro",
    relatedBlogSlug: "gestao-empresarial-completo",
    relatedBlogTitle: "Gestão Empresarial: O Guia Completo para PMEs",
    seoTitle: "Calculadora de Crescimento Mensal e Projeção Anual Grátis | V3X",
    seoDescription: "Calcule a taxa de crescimento mensal da receita e projete o faturamento anual. Veja se sua empresa está no ritmo certo.",
  },
  {
    slug: "calculadora-capacidade-comercial",
    name: "Calculadora de Capacidade Comercial",
    shortName: "Capacidade",
    description: "Descubra o potencial máximo de receita da sua equipe comercial atual.",
    longDescription: "Com base no número de vendedores, leads por vendedor, conversão e ticket médio, calcule o teto de receita que sua estrutura comercial atual consegue atingir.",
    category: "Comercial",
    relatedBlogSlug: "como-montar-equipe-de-vendas",
    relatedBlogTitle: "Como Montar uma Equipe de Vendas de Alta Performance",
    seoTitle: "Calculadora de Capacidade Comercial Grátis | V3X",
    seoDescription: "Descubra o potencial máximo de receita da sua equipe comercial. Calcule quantos leads, vendas e faturamento sua estrutura atual consegue gerar.",
  },
  {
    slug: "calculadora-produtividade-equipe",
    name: "Calculadora de Produtividade da Equipe",
    shortName: "Produtividade",
    description: "Meça a receita por vendedor e por hora para identificar queda de produtividade.",
    longDescription: "Produtividade comercial é receita por vendedor por período. Calcule onde sua equipe está e o quanto uma melhora de produtividade representa em receita adicional.",
    category: "Gestão",
    relatedBlogSlug: "eficiencia-operacional",
    relatedBlogTitle: "Eficiência Operacional: Como Fazer Mais com os Mesmos Recursos",
    seoTitle: "Calculadora de Produtividade da Equipe de Vendas Grátis | V3X",
    seoDescription: "Calcule a produtividade da equipe comercial: receita por vendedor e por hora. Identifique quedas e oportunidades de melhora.",
  },
  {
    slug: "calculadora-tempo-fechamento",
    name: "Calculadora de Tempo Médio de Fechamento",
    shortName: "Ciclo de Venda",
    description: "Calcule o ciclo médio de vendas e projete o impacto de reduzi-lo.",
    longDescription: "O tempo de fechamento define a velocidade do seu pipeline. Saiba o ciclo médio atual e quanto receita adicional você geraria acelerando o processo em dias.",
    category: "Comercial",
    relatedBlogSlug: "follow-up-comercial",
    relatedBlogTitle: "Follow-up Comercial: Como Não Perder Vendas por Falta de Acompanhamento",
    seoTitle: "Calculadora de Tempo Médio de Fechamento de Vendas Grátis | V3X",
    seoDescription: "Calcule o ciclo médio de fechamento de vendas e veja o impacto de reduzi-lo no faturamento mensal.",
  },
  {
    slug: "calculadora-forecast-comercial",
    name: "Calculadora de Forecast Comercial",
    shortName: "Forecast",
    description: "Projete a receita esperada do mês com base nas oportunidades por etapa do funil.",
    longDescription: "Forecast preciso evita surpresas no final do mês. Com base nos leads em cada etapa do funil e nas probabilidades históricas, projete cenários conservador, moderado e otimista.",
    category: "Planejamento",
    relatedBlogSlug: "indicadores-de-vendas",
    relatedBlogTitle: "Indicadores de Vendas: O Dashboard Mínimo para Times Comerciais",
    seoTitle: "Calculadora de Forecast Comercial Grátis | V3X",
    seoDescription: "Projete a receita do mês com forecast por etapa do funil. Cenários conservador, moderado e otimista com base nas probabilidades de fechamento.",
  },
  {
    slug: "calculadora-potencial-faturamento",
    name: "Calculadora de Potencial de Faturamento",
    shortName: "Potencial",
    description: "Projete o faturamento potencial com base na capacidade de geração de leads.",
    longDescription: "Quanto sua empresa poderia faturar se operasse na capacidade máxima? Calcule o potencial de faturamento com base nos leads geráveis, conversão atual e ticket médio.",
    category: "Planejamento",
    relatedBlogSlug: "gestao-empresarial-completo",
    relatedBlogTitle: "Gestão Empresarial: O Guia Completo para PMEs",
    seoTitle: "Calculadora de Potencial de Faturamento Grátis | V3X",
    seoDescription: "Calcule o potencial máximo de faturamento da sua empresa. Projeção por mês com base em leads, conversão e ticket médio.",
  },
];

export function getFerramentaBySlug(slug: string): Ferramenta | undefined {
  return ferramentas.find((f) => f.slug === slug);
}
