"use client";

import { ArrowUpRight, ArrowRight, Clock, CircleCheck } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { useControl } from "./Store";

export function Overview() {
 const { data } = useControl();
 const active = data.projects.filter(p => p.status !== "Completed");
 const pending = data.tasks.filter(t => t.status !== "Completed");
 const deadlines = [...active].sort((a, b) => a.deadline.localeCompare(b.deadline)).slice(0, 4);
 return <main className="mx-auto max-w-[1600px] p-5 md:p-8 lg:p-10">
  <div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><span className="label-mono">FRIDAY, OCTOBER 09, 2026</span><h1 className="mt-3 text-3xl font-medium">Studio overview<span className="text-brand-violet">.</span></h1><p className="mt-2 text-sm text-muted-foreground">A clear view of what&apos;s moving.</p></div><Button render={<Link href="/control/projects" />} nativeButton={false}>View projects <ArrowUpRight /></Button></div>
  <div className="mb-8 flex items-center gap-2 text-[11px] text-muted-foreground"><span className="size-1.5 rounded-full bg-muted-foreground" />Illustrative sample data — not real V3X operations</div>
  <div className="metric-strip">{[["Active projects", active.length, "Across four disciplines"], ["Pending tasks", pending.length, "In the current workspace"], ["Upcoming deadlines", deadlines.length, "Next scheduled deliveries"], ["Active clients", data.clients.filter(c => c.status === "Active").length, "Example relationships"]].map(([label, value, sub]) => <div key={label}><div className="text-xs text-muted-foreground">{label}</div><div className="control-metric-value my-4 text-4xl font-medium">{value}<ArrowUpRight className="ml-3 inline size-4 text-muted-foreground" /></div><div className="text-[10px] text-muted-foreground">{sub}</div></div>)}</div>
  <div className="mt-10 grid gap-10 xl:grid-cols-[1.6fr_1fr]"><section><div className="mb-6 flex items-center justify-between"><h2 className="text-sm font-medium">Project activity</h2><span className="label-mono">OCTOBER / 2026</span></div><div className="flex h-48 items-end gap-3 border-b border-border pb-0">{[34, 51, 45, 68, 52, 84, 72, 95, 67, 84, 97, 79].map((height, i) => <div key={i} className="flex h-full min-w-0 flex-1 flex-col justify-end gap-3"><div className="control-activity-bar transition-colors hover:brightness-125" style={{ height: `${height}%` }} title={`Week ${i + 1}: ${height} illustrative activity units`} /><span className="pb-2 text-center font-mono text-[9px] text-muted-foreground">{String(i + 1).padStart(2, "0")}</span></div>)}</div><div className="mt-6 grid grid-cols-3 gap-4 border-b border-border pb-6">{["In Progress", "In Review", "Completed"].map(status => <div key={status}><div className="text-[11px] text-muted-foreground">{status}</div><div className="mt-2 text-2xl">{data.projects.filter(p => p.status === status).length}</div></div>)}</div></section>
  <section><div className="mb-6 flex justify-between"><h2 className="text-sm font-medium">Upcoming deadlines</h2><Clock className="size-4 text-brand-violet" /></div>{deadlines.map(p => <div key={p.id} className="flex items-center gap-4 border-b border-border py-4"><span className="flex size-10 shrink-0 flex-col items-center justify-center border border-brand-violet/30 bg-brand-violet/10 text-brand-violet text-sm">{p.deadline.slice(8)}<small className="text-[8px] text-muted-foreground">OCT</small></span><div className="min-w-0 flex-1"><p className="truncate text-xs">{p.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{p.category}</p></div><span className="text-[10px] text-muted-foreground">{p.owner}</span></div>)}</section></div>
  <div className="mt-10 grid gap-10 xl:grid-cols-[1.6fr_1fr]"><section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm">In focus</h2><Button variant="link" size="sm" render={<Link href="/control/tasks" />} nativeButton={false}>All tasks <ArrowRight /></Button></div>{pending.slice(0, 3).map(t => <div key={t.id} className="flex items-center gap-4 border-b border-border py-5"><CircleCheck className="size-4 text-brand-blue" /><div className="flex-1"><p className="text-xs">{t.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{t.client}</p></div><span className="control-status" data-status={t.priority}>{t.priority}</span></div>)}</section><section><h2 className="mb-5 text-sm">Recent activity</h2>{[["Isabella", "updated Orbit wireframes", "12 min ago"], ["Matheus", "reviewed Monolith navigation", "48 min ago"], ["Emmanuelle", "prepared the discovery brief", "2 hours ago"]].map(([name, action, time]) => <div key={name} className="flex gap-3 py-3"><span className="mt-1 grid size-7 shrink-0 place-items-center control-avatar rounded-full text-[9px]">{name?.slice(0, 1)}</span><div><p className="text-xs"><span>{name}</span> <span className="text-muted-foreground">{action}</span></p><p className="mt-1 text-[9px] text-muted-foreground">{time} · sample</p></div></div>)}</section></div>
  <section className="mt-10 border-t border-border pt-7"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm">Commercial pipeline</h2><Button variant="link" size="sm" render={<Link href="/control/pipeline" />} nativeButton={false}>View pipeline <ArrowUpRight /></Button></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{["New Lead", "Discovery", "Proposal Sent", "Negotiation"].map(stage => <div key={stage} className="control-pipeline-stage border-l-2 border-border pl-4"><p className="text-xs text-muted-foreground">{stage}</p><p className="my-3 text-2xl">{data.pipeline.filter(lead => lead.status === stage).length}</p>{data.pipeline.filter(lead => lead.status === stage).map(lead => <p key={lead.id} className="text-[11px] text-muted-foreground">{lead.title}</p>)}</div>)}</div><p className="mt-5 text-[10px] text-muted-foreground">Illustrative opportunities only.</p></section>
 </main>;
}
